name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Setup dev environment
        run: "npm run dev:init:remote"
      - name: Build plugin
        run: "npm run dev:build"
      - name: Commit and push Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add .
          git diff --staged --quiet || git commit -m "ci (build): $GITHUB_SHA"

          git checkout develop
          git merge main

          git push --all
