name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Setup dev environment
        run: "npm run dev:init:remote"
      - name: Build plugin
        run: "npm run dev:build"
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "ci (release): build plugin"
          add: "*.js"
